language: python
python:
  - "3.3"
  - "2.7"
  - "2.6"

before_install:
  - sudo apt-get update
  - sudo apt-get install libhdf5-serial-dev

install:
  - pip install .

# command to run tests, e.g. python setup.py test
script:
  - nosetests -v
